# Generated by Django 2.0.3 on 2018-04-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTPComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltp_word_id', models.CharField(max_length=5)),
                ('ltp_word', models.CharField(max_length=30)),
                ('ltp_word_relate', models.CharField(max_length=6)),
                ('ltp_word_parent', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['-product_index_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=120)),
                ('product_category', models.CharField(max_length=50)),
                ('have_data', models.CharField(default='0', max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_comment', models.TextField(blank=True, null=True)),
                ('product_rating', models.CharField(max_length=2)),
                ('comment_split', models.CharField(default='0', max_length=2)),
                ('comment_ltp', models.CharField(default='0', max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('product_index_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_comment.Product')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='SplitComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_word', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('product_index_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_comment.Product')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_id', 'product_name')},
        ),
        migrations.AddField(
            model_name='ltpcomment',
            name='product_comment_index_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_comment.ProductComment'),
        ),
        migrations.AddField(
            model_name='ltpcomment',
            name='product_index_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_comment.Product'),
        ),
    ]
