# Generated by Django 2.0.3 on 2018-05-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_comment', '0002_auto_20180501_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntreatedProductURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untreated_product_url', models.CharField(max_length=220)),
                ('treated', models.CharField(max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.DeleteModel(
            name='UntreatedProduct',
        ),
        migrations.AlterUniqueTogether(
            name='untreatedproducturl',
            unique_together={('untreated_product_url',)},
        ),
    ]
