# Generated by Django 2.0.3 on 2018-05-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_comment', '0005_auto_20180502_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_word', models.CharField(max_length=30, verbose_name='特征词')),
                ('counts', models.IntegerField(verbose_name='频率')),
            ],
            options={
                'verbose_name': '特征词管理',
                'verbose_name_plural': '特征词管理',
                'ordering': ['-product_index_id', '-counts'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='have_data',
            field=models.CharField(max_length=2, verbose_name='是否有此商品的特征词'),
        ),
        migrations.AddField(
            model_name='characterwords',
            name='product_index_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_comment.Product', verbose_name='商品ID'),
        ),
        migrations.AlterUniqueTogether(
            name='characterwords',
            unique_together={('product_index_id', 'character_word')},
        ),
    ]
