# Generated by Django 2.0.3 on 2018-05-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_comment', '0007_characterwords_sentiment_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_index', models.CharField(max_length=22, verbose_name='满意度指标')),
                ('satisfaction_value', models.FloatField(null=True, verbose_name='满意度')),
                ('character_word_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c1', to='product_comment.CharacterWords', verbose_name='特征词1')),
                ('character_word_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='product_comment.CharacterWords', verbose_name='特征词2')),
                ('character_word_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c3', to='product_comment.CharacterWords', verbose_name='特征词3')),
                ('character_word_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c4', to='product_comment.CharacterWords', verbose_name='特征词4')),
                ('character_word_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c5', to='product_comment.CharacterWords', verbose_name='特征词5')),
                ('product_index_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_comment.Product', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '满意度模型管理',
                'verbose_name_plural': '满意度模型管理',
                'ordering': ['-product_index_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='ltpcomment',
            options={'ordering': ['-product_index_id'], 'verbose_name': '依存句法分析结果管理', 'verbose_name_plural': '依存句法分析结果管理'},
        ),
        migrations.AlterModelOptions(
            name='splitcomment',
            options={'ordering': ['-date_time'], 'verbose_name': '分词管理', 'verbose_name_plural': '分词管理'},
        ),
        migrations.AlterUniqueTogether(
            name='satisfactionmodel',
            unique_together={('product_index_id', 'satisfaction_index')},
        ),
    ]
