# Generated by Django 2.0.3 on 2018-05-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_comment', '0010_auto_20180507_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionmodel',
            name='satisfaction_value',
            field=models.FloatField(blank=True, null=True, verbose_name='满意度'),
        ),
    ]
