# Generated by Django 2.0.3 on 2018-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_comment', '0012_auto_20180508_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterwords',
            name='character_word',
            field=models.CharField(max_length=255, verbose_name='特征词'),
        ),
        migrations.AlterField(
            model_name='ltpcomment',
            name='ltp_word',
            field=models.CharField(max_length=255, verbose_name='分词'),
        ),
        migrations.AlterField(
            model_name='ltpcomment',
            name='ltp_word_id',
            field=models.CharField(max_length=255, verbose_name='分词ID'),
        ),
        migrations.AlterField(
            model_name='ltpcomment',
            name='ltp_word_parent',
            field=models.CharField(max_length=255, verbose_name='父节点的索引'),
        ),
        migrations.AlterField(
            model_name='ltpcomment',
            name='ltp_word_relate',
            field=models.CharField(max_length=255, verbose_name='关系'),
        ),
        migrations.AlterField(
            model_name='product',
            name='have_data',
            field=models.CharField(max_length=255, verbose_name='是否有此商品的特征词'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(max_length=255, verbose_name='所属类别'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=255, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment_dict',
            field=models.CharField(max_length=255, null=True, verbose_name='是否进行字典处理'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment_ltp',
            field=models.CharField(max_length=255, verbose_name='是否依存句法分析'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment_split',
            field=models.CharField(max_length=255, verbose_name='是否分词'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product_rating',
            field=models.CharField(max_length=255, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='satisfactionmodel',
            name='satisfaction_index',
            field=models.CharField(max_length=255, verbose_name='满意度指标'),
        ),
        migrations.AlterField(
            model_name='sentimentdict',
            name='word',
            field=models.CharField(max_length=255, verbose_name='情感词'),
        ),
        migrations.AlterField(
            model_name='splitcomment',
            name='split_word',
            field=models.CharField(max_length=255, verbose_name='分词'),
        ),
        migrations.AlterField(
            model_name='untreatedproducturl',
            name='treated',
            field=models.CharField(max_length=255, verbose_name='是否处理过此URL'),
        ),
        migrations.AlterField(
            model_name='untreatedproducturl',
            name='untreated_product_url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
    ]
