# Generated by Django 2.0.3 on 2018-05-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_comment', '0013_auto_20180508_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentimentDict',
        ),
    ]
